### ISSUE TITLE
Separating output by line as in version 1.4.x

### ISSUE THREAD

**Issue by zwhedbee** [ionutvmi/uglifyjs-folder#23]
In version 1.4.x, each JS file found in the specified folder was separated by line in the final minified output. So I'd get something like this:

```
var $x = "this is code from file 1";
var $x = "this is code from file 2";
var $x = "this is code from file 3";
```

After upgrading to version 1.5.x, however, everything is on the same line and it looks like comma separated, like so:

`var $x = "this is code from file 1",var $x = "this is code from file 2",var $x = "this is code from file 3";`

Is there an option I can use to have version 1.5.x separate by line as before? Thanks!

**Comment by ionutvmi** [comment]
is there a reason why you want to have files separated by a new line ?

In version 1.4 we were concatenating all the JS into a large string it before sending it to uglify.
In version 1.5 we let uglify do the concatenation internally which is why it's optimizing those out.

**Comment by ionutvmi** [comment]
You could try something like this:

```
uglifyjs-folder src -o result.js --config-file ./config.json --comments
```

config.json
```
{
    "compress": { "join_vars": false }
}
```

**Comment by zackwhedbee** [comment]
> is there a reason why you want to have files separated by a new line ?

The framework I am using requires the JS files to be loaded in a certain order, so when minified into one file the order that they are concatenated matters. I wrote to essentially rearrange the output of uglifyjs-folder to satisfy that requirement. The script relies on the files being separated by a new line in order to split them up and identify them before rearranging.

Thank you for your solution - that should work after a little modification of my script to account for the comments. Perhaps there is another way I can accomplish this though? Is there a way to specify the order that uglifyjs-folder minifies/concatenates files? Thanks!

**Comment by ionutvmi** [comment]
You could try renaming the files so they are in alphabetical order on the disk.
